### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by suuranna** [lifeofborna/Tiralabra#1]
Repo kloonattu omalle koneelle 10.12.2022 klo 19.10

Tosi hyvältä näyttää! Vautsi vau! :D

Sovellusta on helppo käyttää ja se toimii halutusti. Se tuottaa joka kerralla erilaisia lauseita, jotka ovat suurimmaksi osaksi ihan järkeviä lauseita. Vääränlaisen syötteen antaessa sovellus ei kaadu erroriin vaan se pystyy jatkamaan toimintaansa. Koodi on siistiä ja siitä on helppo ymmärtää, mitä missäkin vaiheessa tapahtuu. Testejäkin on tehty hyvä määrä ja ne näyttävät testaavan ihan olennaisia asioita. :)

Sovellus pyytää käyttäjää antamaan ”ngram sizen”, mutta missään ei sanota, mikä se on ja kaikki käyttäjät eivät varmaan tiedä, mikä ”ngram” on tai miten se tulee vaikuttamaan generoituun lopputulokseen (ellei sitten koodista lähde selvittämään). Näin ollen ehkä vaihtaisin tekstin ”Please select the ngram size recommended (2-5)” johonkin vähän paremmin kuvailevaan tekstiin, jotta käyttäjä ymmärtää, mitä hän on syöttämässä.

Vaikka default- tai ngram-syöte ei ole kokonaisluku, alkaa sovellus kuitenkin muodostamaan trie-treetä ja luomaan todennäköisyyksiä, jolloin jos vaikka ngramin kooksi on annettu 20 ja haluttujen sanojen määräksi yeet, niin sovellus käyttää yli 33 sekuntia trie-treen muodostamiseen ja antaa lopputuloksena tyhjiä lauseita. Käyttäjä ei myöskään saa minkäänlaista virheviestiä, että annettu syöte ei kelpaa. Itse siirtäisin tekstitiedoston lukemisen ja markovin ketjun muodostamisen samaan try-osioon, missä default- ja limit-syötteet annetaan, ja except-osiossa tulostaisin virheviestin.

Hyvää työtä tähän asti! Tsemppiä loppurutistukseen! :D

**Comment by lifeofborna** [comment]
Kiitos korjasin ngram ongelman kun syöte ei ole kokonaisluku.
